pipeline {
    agent any
    stages {
        stage('Check Docker Version') {
            steps {
                script {
                    sh 'docker --version'
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    sh 'docker build -t react-app .'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh 'docker run --rm react-app npm test'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh 'docker run -d -p 80:80 react-app'
                }
            }
        }
    }
}
