version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - redDocker

  wordpress:
    image: wordpress:latest
    container_name: wordpress_web
    restart: always
    ports:
      - "82:80"
    environment:
      WORDPRESS_DB_HOST: mariadb_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - mariadb
    networks:
      - redDocker

networks:
  redDocker:
    external: true
